name: Build Tarballs
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
    zig_release_tag:
      description: "The Zig tag to build"
      required: true
      type: string
      default: ""
concurrency:
  group: tarball
jobs:
  create_tarballs:
    timeout-minutes: 480
    outputs:
      skipped: ${{ steps.build.outputs.skipped }}
    runs-on: [self-hosted, tarballs, x86_64]
    env: 
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ZIG_RELEASE_TAG: ${{ inputs.zig_release_tag }}
    steps:
      - name: Check out code
        with:
          ssh-key: ${{ secrets.TARBALL_COMMIT_SSH_KEY }}
        uses: actions/checkout@v2
      - name: Build Tarballs
        id: build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: ./.github/workflows/build-tarballs.sh
